### ISSUE TITLE
👷‍♀️ Move `irq_flow` building outside of the interrupt manager 

### ISSUE THREAD

**Issue by lukevalenty** [intel/compile-time-init-build#278]
Right now the interrupt manager builds it's own `irq_flow` services. This is complicated and duplicates effort in `cib::nexus`. It also couples the internal details of `cib` services to the implementation of interrupt manager.

This change will remove all `irq_flow` building from the interrupt manager. It will no longer be responsible for building, initializing, or extending its `irq_flow`s. It will also remove the requirement from interrupt manager to support extending the `irq_flow`s.

Instead, the interrupt manager will use regular flows and actions for registering interrupt handlers. 

In order for the interrupt manager to determine whether an interrupt is active or not, it will need access to the nexus.

**Comment by elbeno** [comment]
Resolved with #427
