### ISSUE TITLE
Accept non-narrowing conversions in the `msg::message_base` constructor

### ISSUE THREAD

**Issue by herculanodavi** [intel/compile-time-init-build#315]
In the case of communicating with devices with 8-bit long registers using SPI or I2C, most HAL outputs are arrays of `std::uint8_t`, which could be copied safely to the `msg::message_data` type, `std::uint32_t`.

However, the constructor of `msg::message_base` asserts the `R::value_type` to be `std::uint32_t`, so this cast is not possible.  
```c++
template <detail::range R> explicit constexpr message_base(R const &r) {
    static_assert(std::is_same_v<typename R::value_type, std::uint32_t>);
    resize_and_overwrite(*this, [&](std::uint32_t *dest,
                                    std::size_t max_size) {
        std::copy_n(std::begin(r), std::min(std::size(r), max_size), dest);
        return NumDWordsT;
    });
}
```

Would it make sense to either:
1. Change the `detail::range` concept to add the requirement `std::convertible_to<std::uint32_t>` and remove the `static_assert`?
2. Change the `std::is_same_v` inside the `static_assert` to `std::is_convertible<typename R::value_type, std::uint32_t>`?

I'd be happy to make a PR for that. 

------ 

EDIT: 
Come to think of it, since the `detal::range` concept requires the two iterators, shouldn't the requirement then be `static_assert(std::is_same_v<std::iter_value_t<decltype(std::begin(r))>, std::uint32_t>);` even if no conversions are allowed? Then the `value_type` of the iterator is required, rather than that of the container. This would allow types like `uint32_t[N]` and `std::ranges::transform_view` to be inputs to message.

**Comment by herculanodavi** [comment]
Thank you! This solves it for now, though using other types as storage would also be great. 

I see the issue is still open, so should I close it or would it be closed when the todo is done?

**Comment by bdeane-intel** [comment]
Let's leave it open as a TODO. I think @mjcaisse-intel already has an implementation, so hopefully we can get that into cib soon.
