### ISSUE TITLE
💡 `indexed_handler`: Add support for sum of product predicates on indexed fields.

### ISSUE THREAD

**Issue by lukevalenty** [intel/compile-time-init-build#373]
Once #370 and #371 are implemented, we will still want support for efficient lookup of callbacks with "sum of product" style predicates. This will allow more matcher formula to be put into the index for fast lookup.

**Comment by elbeno** [comment]
To be clear, "sum of products" here means "disjunction of conjunctions" i.e. OR of ANDs.
