### ISSUE TITLE
Compiling with standard c++17

### ISSUE THREAD

**Issue by tunguskar** [intel/compile-time-init-build#439]
Hi 

At the moment I just wanted to include your library. Im stuck to c++17, so I use the version v1.7.0. The problem I Sie is as follows. 

- FetchContent to the library
- add library to my library: target_link_libraries(${LIBRARY_NAME} PRIVATE cib)
- In my lib I just included the default header: #include <cib/cib.hpp>
- When I now compile I get many errors. The first is: \_deps\cib-src\include\cib/tuple.hpp(67): error C3520: "IndexTs": In this context the parameter packet has to be extended. 

I first thought the c++ standard could be wrong and checked in the lib cmakeLists before I included the cib library the cxx standard:

![image](https://github.com/intel/compile-time-init-build/assets/2837624/59e1d0c3-9572-45b7-ada5-d647fc496008)

Have you any thoughts whats wrong here?

**Comment by lukevalenty** [comment]
What compiler and version are you using?

**Comment by tunguskar** [comment]
I tried both, clang and gcc. 
But my main compiler on this is clang in version 17.05. I tried now to use your compiler explorer example from here:

https://github.com/intel/compile-time-init-build/tree/v1.7.0#hello-world

I just copied the raw code of the header and added the hello world. The `compile_commands.json` file looks like this: 

-O3 -DNDEBUG -std=gnu++17 -D_DLL -D_MT -Xclang --dependent-lib=msvcrt -o

For example catch2 is part of this test project and this compiles fine. The first error I get is this: 

```text
[build] In file included from test_cpp_testcib.cpp:6:
[build] cib.hpp:779:9: error: no matching function for call to 'quicksort'
[build]   779 |         quicksort(std::begin(collection), 0, std::size(collection) - std::size_t{1});
[build]       |         ^~~~~~~~~

```

this is weird because the template function is above:

![image](https://github.com/intel/compile-time-init-build/assets/2837624/10349da7-9006-49f6-8ecf-aa3d6de02519)

**Comment by elbeno** [comment]
`quicksort` is expecting a `T*` as the first argument and we are calling it with `std::begin(collection)` - an array iterator. I just made a change to the cpp17 branch that should fix this? (Although I'm not sure why it's only seen just now.)

**Comment by tunguskar** [comment]
@elbeno @lukevalenty Hello World compiles now so far. Even I do not really get your code so far, it was exactly what I was searching for from a mindset point of view, thanks for your effort and help so far!

**Comment by elbeno** [comment]
This looks like the same cause as before. (No implicit conversion from iterator to pointer.) Which STL are you using?

**Comment by elbeno** [comment]
https://github.com/intel/compile-time-init-build/commit/575d3cc0ea0d7c0664618ec66bec967272cfa58a fixes a few of these issues I've found. But it looks like you are using a different STL (not libc++ or libstdc++?) that flags these issues... I don't see them.

**Comment by tunguskar** [comment]
my cpp test file is compiled with the following options: -O3 -DNDEBUG -std=gnu++17 -D_DLL -D_MT -Xclang --dependent-lib=msvcrt

Could it be that the msvcrt is the problem on my windows machine?

**Comment by elbeno** [comment]
The iterator/pointer conversion issue was just something that happened to work in libstdc++ I guess, so fixing that is good. However to go back to your original error:

`_deps\cib-src\include\cib/tuple.hpp(67): error C3520: "IndexTs": In this context the parameter packet has to be extended.`

This is just a language thing - nothing to do with the STL variant. It's a variadic using declaration, new in C++17.

**Comment by tunguskar** [comment]
> The iterator/pointer conversion issue was just something that happened to work in libstdc++ I guess, so fixing that is good. However to go back to your original error:
> 
> `_deps\cib-src\include\cib/tuple.hpp(67): error C3520: "IndexTs": In this context the parameter packet has to be extended.`
> 
> This is just a language thing - nothing to do with the STL variant. It's a variadic using declaration, new in C++17.

So in your opinion it should compile on a windows machine with clang?

**Comment by elbeno** [comment]
I don't see anything wrong with https://github.com/intel/compile-time-init-build/blob/cpp17/include/cib/tuple.hpp#L67 so I'm not sure why the MS compiler is complaining. This is well-formed C++17 as far as I can see. It looks like the MS compiler has had bugs in this area at times (e.g. https://stackoverflow.com/questions/71738552/c3520-parameter-pack-must-be-expanded-incorrect-behaviour-for-variadic-using) - maybe this is such a case.

**Comment by tunguskar** [comment]
Thanks for your Investigation.
