### ISSUE TITLE
Messages support for uint8_t

### ISSUE THREAD

**Issue by Thurnheer** [intel/compile-time-init-build#446]
It would be nice if the messages would support the creation of owning uint8_t messages.
As for example Uart communication is normaly not a multiple of dword, it would be nice to have support for creation (owning) of uint8_t based messages.

**Comment by lukevalenty** [comment]
Hey @bdeane-intel, does the message refactor support multiple underlying storage widths?

**Comment by Thurnheer** [comment]
@lukevalenty it seems to do. I would have a PR.

**Comment by elbeno** [comment]
Yep, already supported. I just added a test to demonstrate - customize the storage type passed to `owner_t`. See #315 and #448.
