### ISSUE TITLE
String constant header fails to compile

### ISSUE THREAD

**Issue by DolphinGui** [intel/compile-time-init-build#618]
When compiling under clang 18.1.8, string_constant.hpp fails to compile because `uint64_t` is not defined.

**Comment by elbeno** [comment]
Can you be more specific? CI runs clang 18 with both libstdc++ and libc++; I am running clang 18.1.8 and I am unable to reproduce this issue.

**Comment by DolphinGui** [comment]
Upon updating the cib commit version hash, the problem seems to have gone away. I was using 476c583, but it seems to have been fixed already.
